### ISSUE TITLE
Survivor Interaction Tool: Place Carosel at Top, Rotate Images

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#1414] opened 2022-06-27 14:32 UTC
**Describe the problem**
When visiting the Survivor Interaction page and clicking on an image, the image loads in the vertical center of the page. Unfortunately, that page has grown significantly over time, and you have to scroll to find the image. 
Also, the image is often 90 degrees to the left. 

**Describe the solution**
1. When viewing an image on this page, place the image carosel in the center of the current view, rather than the vertical center of the window.
2. If the Carosel widget has a "turn 90 degrees" feature, then please add it.
3. Also, please make sure that images are being crunched and compressed when they are placed on Print PDF.

**Additional context and instructions**

**Comment by deepanchal** [comment] 2022-08-31 16:19
Maybe duplicate of #1341 
Maybe fixed by #1451

**Closed by deepanchal** 2022-08-31 16:19 UTC
Labels: enhancement, ui, ux, feature_request
