### ISSUE TITLE
Increase Toasted Error time to at least 7 seconds

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#620] opened 2020-04-16 04:04 UTC
**Describe the problem**
Toasted errors disappear too fast.

**Describe the solution**
Universally increase the Toasted error time to at least 7 seconds.

**Additional context and instructions**

**Comment by BradenM** [comment] 2020-04-16 06:33
Duplicate of #595 and was closed in  6ddfaab

**Closed by BradenM** 2020-04-16 06:33 UTC
Labels: easy, enhancement, good first issue, ui, ux
