### ISSUE TITLE
Request Invitation Approve and Reject Does not Work

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-3-web#674] opened 2020-05-06 18:49 UTC
**Describe the bug**
After a prospective user requests access, the request appears on "Invitation Management." The "Reject" and "Accept" buttons do not work.

This is a recurring issue. See #625 

**To Reproduce**
1. Go to https://www.crisiscleanup.org/organization/invitations
2. Click on a Reject or Accept button
3. Nothing happens

**Expected behavior**
1. If accepted, ghost user information is copied to the user table, and the applying user is notified, and the request disappears from the list.
2. If ignored, no action is taken and the request disappears from THAT USER's list only, but remains on other users' lists.
3. If rejected, the rejection is recorded, the applying ghost_user is notified via email, and the rejecting user gets to add a short optional note to the notification.
4. The person can later request access to the same or a different individual in the future.
Please write a test to ensure this does not break again.

**Screenshots**
![Invitation Actions Broken](https://user-images.githubusercontent.com/4184619/81209498-dbdbd780-8f8d-11ea-99f3-697350d47631.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wodow** [comment] 2020-05-12 09:57
can't reproduce in dev, at `1b35836f8150ff427535` -- both buttons work ok

**Comment by BradenM** [comment] 2020-05-24 08:23
Closed by CrisisCleanup/crisiscleanup-3-api#240

**Closed by BradenM** 2020-05-24 08:23 UTC
Labels: bug, easy, good first issue, ui, users, ux

**Comment by aarontitus** [comment] 2020-05-24 13:24
Confirmed it's working on dev now.
